# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 5000

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$custom\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$deno\
$elixir\
$golang\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$aws\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"

[aws]
force_display = true
[aws.profile_aliases]
datalake-deploy = "eLib::datalake-deploy"
datalake-dev = "eLib::datalake-dev"
datalake-prod = "eLib::datalake-prod"
datalake-test = "eLib::datalake-test"
eventbridge-dev = "eLib::eventbridge-dev"
eventbridge-prod = "eLib::eventbridge-prod"
eventbridge-test = "eLib::eventbridge-test"

[kubernetes]
disabled = false
style = "bold #3970e4"

[custom.git-profile]
command = 'git config --get user.name'
when = 'git rev-parse --is-inside-work-tree'
require_repo = true
description = 'Display git user.name'
symbol = ""
style = "fg:#b16286 bold"
format = '[$symbol ($output)]($style) '

