# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 5000

# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"

[aws]
force_display = true
[aws.profile_aliases]
datalake-deploy = "eLib::datalake-deploy"
datalake-dev = "eLib::datalake-dev"
datalake-prod = "eLib::datalake-prod"
datalake-test = "eLib::datalake-test"
eventbridge-dev = "eLib::eventbridge-dev"
eventbridge-prod = "eLib::eventbridge-prod"
eventbridge-test = "eLib::eventbridge-test"
