# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"
